# Generated by Django 4.2.5 on 2023-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda ', 'Rwanda'), ('Congo', 'Congo'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria')], max_length=24),
        ),
    ]
