
# version: 2

# models:
#   - name: aggregate_imdb
#     description: "Grouped dataset by sentiment col"
#     columns:
#       - name: sentiment
#         description: "The sentiment value for this dataset"
#         tests:
#           - not_null

#       - name: id
#         description: unique_id
#         tests:
#           - unique

#   - name: neg_sents
#     description: "only negative records"
#     columns:
#       - name: sentiment
#         description: "The sentiment value for the dataset"
#         tests:
#           - not_null

#       - name: id
#         description: "unique_id"
#         tests:
#           - unique

#   - name: pos_sents
#     description: "only positive records"
#     columns:
#       - name: sentiment
#         description: "The sentiment value for the dataset"
#         tests:
#           - not_null

#       - name: id
#         description: "unique_id"
#         tests:
#           - unique

